FROM node:20.12.0 

WORKDIR /app

COPY package.json package-lock.json tubro.json tsconfig.json ./

COPY apps ./apps
COPY package  ./packages

RUN npm install

run npm run db:generate

CMD ["npm","run","start-user-app"]